/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as LoansIndexRouteImport } from './routes/loans.index'
import { Route as LoansLoanIdRouteImport } from './routes/loans.$loanId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoansRoute,
} as any)
const LoansLoanIdRoute = LoansLoanIdRouteImport.update({
  id: '/$loanId',
  path: '/$loanId',
  getParentRoute: () => LoansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/collections': typeof CollectionsRoute
  '/loans': typeof LoansRouteWithChildren
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/collections': typeof CollectionsRoute
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans': typeof LoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/collections': typeof CollectionsRoute
  '/loans': typeof LoansRouteWithChildren
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/clients' | '/collections' | '/loans' | '/loans/$loanId' | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clients' | '/collections' | '/loans/$loanId' | '/loans'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/collections'
    | '/loans'
    | '/loans/$loanId'
    | '/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  CollectionsRoute: typeof CollectionsRoute
  LoansRoute: typeof LoansRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof LoansRoute
    }
    '/loans/$loanId': {
      id: '/loans/$loanId'
      path: '/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof LoansLoanIdRouteImport
      parentRoute: typeof LoansRoute
    }
  }
}

interface LoansRouteChildren {
  LoansLoanIdRoute: typeof LoansLoanIdRoute
  LoansIndexRoute: typeof LoansIndexRoute
}

const LoansRouteChildren: LoansRouteChildren = {
  LoansLoanIdRoute: LoansLoanIdRoute,
  LoansIndexRoute: LoansIndexRoute,
}

const LoansRouteWithChildren = LoansRoute._addFileChildren(LoansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  CollectionsRoute: CollectionsRoute,
  LoansRoute: LoansRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
